all: shamirenc shamirdec
	corebuild TmpFiniteShamirenc.native
	corebuild TmpFiniteShamirdec.native

shamirenc: 
	corebuild TmpFiniteShamirenc.native

shamirdec:
	corebuild TmpFiniteShamirdec.native

clean:
	rm -rf _build *.native
